/**
 * Lua script for atomic rate-limit acquisition.
 *
 * Embedded as a TypeScript string so it is available inside the compiled
 * dist/ tree without any file-system path resolution at runtime. Loading from
 * a .lua file would break because NestJS nest build copies only *.js/*.d.ts.
 *
 * Keys and arguments
 * numberOfKeys = 2
 *
 * KEYS[1]  active_calls:{apiKeyId}   Redis SET   - members = in-flight call IDs
 * KEYS[2]  cps:{apiKeyId}            Redis ZSET  - score = ms timestamp, member = call ID
 *
 * ARGV[1]  maxConcurrent   (integer) maximum simultaneous in-flight calls
 * ARGV[2]  maxCps          (integer) maximum call-creates per rolling 1-second window
 * ARGV[3]  nowMs           (integer) current Unix epoch in milliseconds
 * ARGV[4]  windowMs        (integer) CPS rolling window width in ms (always 1000)
 * ARGV[5]  callId          (string)  UUID pre-generated by the application
 * ARGV[6]  setTtlSeconds   (integer) safety TTL on the SET (mirrors CALL_STATE_TTL_SECONDS)
 *
 * Return values
 * {1, 'OK'}           - both limits satisfied; call has been reserved
 * {0, 'CPS'}          - CPS limit would be exceeded; call rejected
 * {0, 'CONCURRENCY'}  - concurrency limit would be exceeded; call rejected
 *
 * Check order rationale
 * CPS is checked first because it is cheaper (ZCARD after one ZREMRANGEBYSCORE
 * vs SCARD which can be large). More importantly, CPS is the burst-protection
 * limit: a caller hammering the endpoint at 100 req/s should see CPS errors,
 * not CONCURRENCY errors that might confusingly hint at call clean-up issues.
 *
 * Atomicity guarantee
 * Because Redis is single-threaded and Lua scripts run atomically (no other
 * command can interleave), the check-then-act sequence is race-free without
 * any separate WATCH/MULTI/EXEC.
 */
export const RATE_LIMIT_ACQUIRE_LUA = `
local activeKey  = KEYS[1]
local cpsKey     = KEYS[2]

local maxConcurrent = tonumber(ARGV[1])
local maxCps        = tonumber(ARGV[2])
local nowMs         = tonumber(ARGV[3])
local windowMs      = tonumber(ARGV[4])
local callId        = ARGV[5]
local setTtlSecs    = tonumber(ARGV[6])

-- Step 1: evict CPS entries that have aged out of the rolling window
-- Entries with score < (nowMs - windowMs) are outside the 1-second window.
local windowStart = nowMs - windowMs
redis.call('ZREMRANGEBYSCORE', cpsKey, 0, windowStart)

-- Step 2: CPS gate
-- If the ZSET already holds maxCps or more entries the window is full.
if redis.call('ZCARD', cpsKey) >= maxCps then
  return {0, 'CPS'}
end

-- Step 3: Concurrency gate
-- If the SET already holds maxConcurrent or more members the slot pool is full.
if redis.call('SCARD', activeKey) >= maxConcurrent then
  return {0, 'CONCURRENCY'}
end

-- Step 4: Reserve the call
-- Add the callId to both the CPS ZSET and the active-calls SET.
-- Use the ms timestamp as the ZSET score so ZREMRANGEBYSCORE works correctly.
redis.call('ZADD', cpsKey, nowMs, callId)
-- Cap the ZSET lifetime to the rolling window so it self-cleans even if the
-- member is never explicitly removed.
redis.call('PEXPIRE', cpsKey, windowMs)

redis.call('SADD', activeKey, callId)
-- Safety TTL: if the worker process crashes before removing the call from
-- the active SET, the SET will expire on its own after setTtlSecs seconds.
-- This matches CALL_STATE_TTL_SECONDS so the safety window equals the maximum
-- expected call lifetime.
redis.call('EXPIRE', activeKey, setTtlSecs)

return {1, 'OK'}
`;
